version: '3.8'

services:
  invoice-processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: invoice-processor-api
    container_name: invoice-processor
    ports:
      - "8000:8000"
    volumes:
      - ./test_images:/app/test_images
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s